#!/bin/bash

UNITS_DIV="/1024"
UNITS="MB"
VERBOSE=false

while [ $# -gt 0 ]; do
	case "$1" in
	-g)
		UNITS_DIV="/1024/1024"
		UNITS="GB"
		;;
	-k)
		UNITS_DIV=""
		UNITS="kB"
		;;
	-v)
		VERBOSE=true
		;;	
	esac

	shift
done

mem_total=$((`cat /proc/meminfo | awk '/^MemTotal/ { print $2; }'`$UNITS_DIV))
mem_free=$((`cat /proc/meminfo | awk '/^MemFree/ { print $2; }'`$UNITS_DIV))
swap_free=$((`cat /proc/meminfo | awk '/^SwapFree/ { print $2; }'`$UNITS_DIV))
swap_total=$((`cat /proc/meminfo | awk '/^SwapTotal/ { print $2; }'`$UNITS_DIV))

arc_c_max=$((`cat /proc/spl/kstat/zfs/arcstats | grep -P '^c_max' | awk '{ print $3; }'`/1024$UNITS_DIV))
arc_c=$((`cat /proc/spl/kstat/zfs/arcstats | grep -P '^c\s' | awk '{ print $3; }'`/1024$UNITS_DIV))
arc_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^size/ { print $3; }'`/1024$UNITS_DIV))
arc_mfu_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^mfu_size/ { print $3; }'`/1024$UNITS_DIV))
arc_mfu_ghost_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^mfu_ghost_size/ { print $3; }'`/1024$UNITS_DIV))
arc_mru_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^mru_size/ { print $3; }'`/1024$UNITS_DIV))
arc_mru_ghost_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^mru_ghost_size/ { print $3; }'`/1024$UNITS_DIV))
arc_meta_limit=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^arc_meta_limit/ { print $3; }'`/1024$UNITS_DIV))
arc_meta_max=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^arc_meta_max/ { print $3; }'`/1024$UNITS_DIV))
arc_meta_used=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^arc_meta_used/ { print $3; }'`/1024$UNITS_DIV))
arc_hdr_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^hdr_size/ { print $3; }'`/1024$UNITS_DIV))
arc_l2_hdr_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^l2_hdr_size/ { print $3; }'`/1024$UNITS_DIV))
arc_dnode_limit=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^arc_dnode_limit/ { print $3; }'`/1024$UNITS_DIV))
dnode_size=$((`cat /proc/spl/kstat/zfs/arcstats | awk '/^dnode_size/ { print $3; }'`/1024$UNITS_DIV))
slab_size=$((`cat /proc/meminfo | awk '/^Slab/ { print $2; }'`$UNITS_DIV))
pagecache_size=$((`cat /proc/meminfo | awk '/^Cached/ { print $2; }'`$UNITS_DIV))
swapcache_size=$((`cat /proc/meminfo | awk '/^SwapCached/ { print $2; }'`$UNITS_DIV))
buffers_size=$((`cat /proc/meminfo | awk '/^Buffers/ { print $2; }'`$UNITS_DIV))
mem_free_no_cache=$(( $mem_free + $swapcache_size + $buffers_size))
swap_used=$(( $swap_total - $swap_free ))
committed=$((`cat /proc/meminfo | awk '/^Committed_AS/ { print $2; }'`$UNITS_DIV))

printf "mem_total             %12s $UNITS\n" $mem_total
printf "mem_free              %12s $UNITS\n" $mem_free
printf "mem_free_no_cache     %12s $UNITS\n" $mem_free_no_cache
printf "mem_swap_free         %12s $UNITS\n" $swap_free
printf "mem_swap_used         %12s $UNITS\n" $swap_used
printf "slab_size             %12s $UNITS\n" $slab_size
printf "pagecache_size           %12s $UNITS\n" $pagecache_size
printf "swapcache_size        %12s $UNITS\n" $swapcache_size
$VERBOSE && \
printf "buffers_size          %12s $UNITS\n" $buffers_size
$VERBOSE && \
printf "committed             %12s $UNITS\n" $committed
printf "\n"
printf "arc_c_max             %12s $UNITS\n" $arc_c_max
printf "arc_c                 %12s $UNITS\n" $arc_c
printf "arc_size              %12s $UNITS\n" $arc_size
$VERBOSE && \
printf "arc_hdr_size          %12s $UNITS\n" $arc_hdr_size
$VERBOSE && \
printf "arc_l2_hdr_size       %12s $UNITS\n" $arc_l2_hdr_size
printf "arc_mfu_size          %12s $UNITS\n" $arc_mfu_size
$VERBOSE && \
printf "arc_mfu_ghost_size    %12s $UNITS\n" $arc_mfu_ghost_size
printf "arc_mru_size          %12s $UNITS\n" $arc_mru_size
$VERBOSE && \
printf "arc_mru_ghost_size    %12s $UNITS\n" $arc_mru_ghost_size
printf "arc_meta_limit        %12s $UNITS\n" $arc_meta_limit
printf "arc_meta_used         %12s $UNITS\n" $arc_meta_used
$VERBOSE && \
printf "arc_meta_max          %12s $UNITS\n" $arc_meta_max
$VERBOSE && \
printf "arc_dnode_limit       %12s $UNITS\n" $arc_dnode_limit
$VERBOSE && \
printf "dnode_size            %12s $UNITS\n" $dnode_size
